#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioAlumnos.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EjercicioAlumnos")]
	public partial class DatosAlumnosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertCiudad(Ciudad instance);
    partial void UpdateCiudad(Ciudad instance);
    partial void DeleteCiudad(Ciudad instance);
    partial void InsertPais(Pais instance);
    partial void UpdatePais(Pais instance);
    partial void DeletePais(Pais instance);
    partial void InsertPersonalDocenteNoDocente(PersonalDocenteNoDocente instance);
    partial void UpdatePersonalDocenteNoDocente(PersonalDocenteNoDocente instance);
    partial void DeletePersonalDocenteNoDocente(PersonalDocenteNoDocente instance);
    partial void InsertProvincia(Provincia instance);
    partial void UpdateProvincia(Provincia instance);
    partial void DeleteProvincia(Provincia instance);
    partial void InsertSexo(Sexo instance);
    partial void UpdateSexo(Sexo instance);
    partial void DeleteSexo(Sexo instance);
    partial void InsertTipoDocumento(TipoDocumento instance);
    partial void UpdateTipoDocumento(TipoDocumento instance);
    partial void DeleteTipoDocumento(TipoDocumento instance);
    partial void InsertTipoPersonal(TipoPersonal instance);
    partial void UpdateTipoPersonal(TipoPersonal instance);
    partial void DeleteTipoPersonal(TipoPersonal instance);
    partial void InsertTipoUsuario(TipoUsuario instance);
    partial void UpdateTipoUsuario(TipoUsuario instance);
    partial void DeleteTipoUsuario(TipoUsuario instance);
    #endregion
		
		public DatosAlumnosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EjercicioAlumnosConnectionString4"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatosAlumnosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosAlumnosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosAlumnosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosAlumnosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Alumno> Alumno
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Ciudad> Ciudad
		{
			get
			{
				return this.GetTable<Ciudad>();
			}
		}
		
		public System.Data.Linq.Table<Pais> Pais
		{
			get
			{
				return this.GetTable<Pais>();
			}
		}
		
		public System.Data.Linq.Table<PersonalDocenteNoDocente> PersonalDocenteNoDocente
		{
			get
			{
				return this.GetTable<PersonalDocenteNoDocente>();
			}
		}
		
		public System.Data.Linq.Table<Provincia> Provincia
		{
			get
			{
				return this.GetTable<Provincia>();
			}
		}
		
		public System.Data.Linq.Table<Sexo> Sexo
		{
			get
			{
				return this.GetTable<Sexo>();
			}
		}
		
		public System.Data.Linq.Table<TipoDocumento> TipoDocumento
		{
			get
			{
				return this.GetTable<TipoDocumento>();
			}
		}
		
		public System.Data.Linq.Table<TipoPersonal> TipoPersonal
		{
			get
			{
				return this.GetTable<TipoPersonal>();
			}
		}
		
		public System.Data.Linq.Table<TipoUsuario> TipoUsuario
		{
			get
			{
				return this.GetTable<TipoUsuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _a_idalumno;
		
		private System.Nullable<long> _a_id_tipo_documento;
		
		private string _a_nrodocumento;
		
		private string _a_nombre;
		
		private string _a_apellido;
		
		private System.Nullable<System.DateTime> _a_fecha_nacimiento;
		
		private System.Nullable<long> _a_sexo;
		
		private string _a_direccion;
		
		private System.Nullable<long> _a_id_ciudadnacimiento;
		
		private System.Nullable<long> _a_idpcianacimiento;
		
		private System.Nullable<long> _a_idpaisnacimiento;
		
		private string _a_mail;
		
		private string _a_cuil;
		
		private string _a_telefonofijo;
		
		private string _a_telefonocelular;
		
		private string _a_contactoemergencia;
		
		private string _a_direccionresidencia;
		
		private System.Nullable<long> _a_idciudadresidencia;
		
		private System.Nullable<long> _a_pciaresidencia;
		
		private System.Nullable<long> _a_paisresidencia;
		
		private string _a_telefonofijoresidencia;
		
		private string _a_telefonocelularresidencia;
		
		private System.Nullable<int> _a_activo;
		
		private System.Nullable<System.DateTime> _a_fechaaltasistema;
		
		private System.Nullable<System.DateTime> _a_fechaultimaactualizacion;
		
		private System.Data.Linq.Binary _a_foto;
		
		private System.Nullable<long> _Nivelestudio;
		
		private System.Nullable<long> _Idtipousuario;
		
		private System.Nullable<long> _a_Idempresa;
		
		private System.Nullable<long> _a_idmodoingreso;
		
		private System.Nullable<long> _a_idestadoalumno;
		
		private EntityRef<Ciudad> _Ciudad;
		
		private EntityRef<Ciudad> _Ciudad1;
		
		private EntityRef<Pais> _Pais;
		
		private EntityRef<Pais> _Pais1;
		
		private EntityRef<Provincia> _Provincia;
		
		private EntityRef<Provincia> _Provincia1;
		
		private EntityRef<TipoUsuario> _TipoUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ona_idalumnoChanging(long value);
    partial void Ona_idalumnoChanged();
    partial void Ona_id_tipo_documentoChanging(System.Nullable<long> value);
    partial void Ona_id_tipo_documentoChanged();
    partial void Ona_nrodocumentoChanging(string value);
    partial void Ona_nrodocumentoChanged();
    partial void Ona_nombreChanging(string value);
    partial void Ona_nombreChanged();
    partial void Ona_apellidoChanging(string value);
    partial void Ona_apellidoChanged();
    partial void Ona_fecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Ona_fecha_nacimientoChanged();
    partial void Ona_sexoChanging(System.Nullable<long> value);
    partial void Ona_sexoChanged();
    partial void Ona_direccionChanging(string value);
    partial void Ona_direccionChanged();
    partial void Ona_id_ciudadnacimientoChanging(System.Nullable<long> value);
    partial void Ona_id_ciudadnacimientoChanged();
    partial void Ona_idpcianacimientoChanging(System.Nullable<long> value);
    partial void Ona_idpcianacimientoChanged();
    partial void Ona_idpaisnacimientoChanging(System.Nullable<long> value);
    partial void Ona_idpaisnacimientoChanged();
    partial void Ona_mailChanging(string value);
    partial void Ona_mailChanged();
    partial void Ona_cuilChanging(string value);
    partial void Ona_cuilChanged();
    partial void Ona_telefonofijoChanging(string value);
    partial void Ona_telefonofijoChanged();
    partial void Ona_telefonocelularChanging(string value);
    partial void Ona_telefonocelularChanged();
    partial void Ona_contactoemergenciaChanging(string value);
    partial void Ona_contactoemergenciaChanged();
    partial void Ona_direccionresidenciaChanging(string value);
    partial void Ona_direccionresidenciaChanged();
    partial void Ona_idciudadresidenciaChanging(System.Nullable<long> value);
    partial void Ona_idciudadresidenciaChanged();
    partial void Ona_pciaresidenciaChanging(System.Nullable<long> value);
    partial void Ona_pciaresidenciaChanged();
    partial void Ona_paisresidenciaChanging(System.Nullable<long> value);
    partial void Ona_paisresidenciaChanged();
    partial void Ona_telefonofijoresidenciaChanging(string value);
    partial void Ona_telefonofijoresidenciaChanged();
    partial void Ona_telefonocelularresidenciaChanging(string value);
    partial void Ona_telefonocelularresidenciaChanged();
    partial void Ona_activoChanging(System.Nullable<int> value);
    partial void Ona_activoChanged();
    partial void Ona_fechaaltasistemaChanging(System.Nullable<System.DateTime> value);
    partial void Ona_fechaaltasistemaChanged();
    partial void Ona_fechaultimaactualizacionChanging(System.Nullable<System.DateTime> value);
    partial void Ona_fechaultimaactualizacionChanged();
    partial void Ona_fotoChanging(System.Data.Linq.Binary value);
    partial void Ona_fotoChanged();
    partial void OnNivelestudioChanging(System.Nullable<long> value);
    partial void OnNivelestudioChanged();
    partial void OnIdtipousuarioChanging(System.Nullable<long> value);
    partial void OnIdtipousuarioChanged();
    partial void Ona_IdempresaChanging(System.Nullable<long> value);
    partial void Ona_IdempresaChanged();
    partial void Ona_idmodoingresoChanging(System.Nullable<long> value);
    partial void Ona_idmodoingresoChanged();
    partial void Ona_idestadoalumnoChanging(System.Nullable<long> value);
    partial void Ona_idestadoalumnoChanged();
    #endregion
		
		public Alumno()
		{
			this._Ciudad = default(EntityRef<Ciudad>);
			this._Ciudad1 = default(EntityRef<Ciudad>);
			this._Pais = default(EntityRef<Pais>);
			this._Pais1 = default(EntityRef<Pais>);
			this._Provincia = default(EntityRef<Provincia>);
			this._Provincia1 = default(EntityRef<Provincia>);
			this._TipoUsuario = default(EntityRef<TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_idalumno", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long a_idalumno
		{
			get
			{
				return this._a_idalumno;
			}
			set
			{
				if ((this._a_idalumno != value))
				{
					this.Ona_idalumnoChanging(value);
					this.SendPropertyChanging();
					this._a_idalumno = value;
					this.SendPropertyChanged("a_idalumno");
					this.Ona_idalumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id_tipo_documento", DbType="BigInt")]
		public System.Nullable<long> a_id_tipo_documento
		{
			get
			{
				return this._a_id_tipo_documento;
			}
			set
			{
				if ((this._a_id_tipo_documento != value))
				{
					this.Ona_id_tipo_documentoChanging(value);
					this.SendPropertyChanging();
					this._a_id_tipo_documento = value;
					this.SendPropertyChanged("a_id_tipo_documento");
					this.Ona_id_tipo_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_nrodocumento", DbType="NVarChar(20)")]
		public string a_nrodocumento
		{
			get
			{
				return this._a_nrodocumento;
			}
			set
			{
				if ((this._a_nrodocumento != value))
				{
					this.Ona_nrodocumentoChanging(value);
					this.SendPropertyChanging();
					this._a_nrodocumento = value;
					this.SendPropertyChanged("a_nrodocumento");
					this.Ona_nrodocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_nombre", DbType="NVarChar(MAX)")]
		public string a_nombre
		{
			get
			{
				return this._a_nombre;
			}
			set
			{
				if ((this._a_nombre != value))
				{
					this.Ona_nombreChanging(value);
					this.SendPropertyChanging();
					this._a_nombre = value;
					this.SendPropertyChanged("a_nombre");
					this.Ona_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_apellido", DbType="NVarChar(MAX)")]
		public string a_apellido
		{
			get
			{
				return this._a_apellido;
			}
			set
			{
				if ((this._a_apellido != value))
				{
					this.Ona_apellidoChanging(value);
					this.SendPropertyChanging();
					this._a_apellido = value;
					this.SendPropertyChanged("a_apellido");
					this.Ona_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_fecha_nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> a_fecha_nacimiento
		{
			get
			{
				return this._a_fecha_nacimiento;
			}
			set
			{
				if ((this._a_fecha_nacimiento != value))
				{
					this.Ona_fecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._a_fecha_nacimiento = value;
					this.SendPropertyChanged("a_fecha_nacimiento");
					this.Ona_fecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_sexo", DbType="BigInt")]
		public System.Nullable<long> a_sexo
		{
			get
			{
				return this._a_sexo;
			}
			set
			{
				if ((this._a_sexo != value))
				{
					this.Ona_sexoChanging(value);
					this.SendPropertyChanging();
					this._a_sexo = value;
					this.SendPropertyChanged("a_sexo");
					this.Ona_sexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_direccion", DbType="NVarChar(MAX)")]
		public string a_direccion
		{
			get
			{
				return this._a_direccion;
			}
			set
			{
				if ((this._a_direccion != value))
				{
					this.Ona_direccionChanging(value);
					this.SendPropertyChanging();
					this._a_direccion = value;
					this.SendPropertyChanged("a_direccion");
					this.Ona_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id_ciudadnacimiento", DbType="BigInt")]
		public System.Nullable<long> a_id_ciudadnacimiento
		{
			get
			{
				return this._a_id_ciudadnacimiento;
			}
			set
			{
				if ((this._a_id_ciudadnacimiento != value))
				{
					if (this._Ciudad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ona_id_ciudadnacimientoChanging(value);
					this.SendPropertyChanging();
					this._a_id_ciudadnacimiento = value;
					this.SendPropertyChanged("a_id_ciudadnacimiento");
					this.Ona_id_ciudadnacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_idpcianacimiento", DbType="BigInt")]
		public System.Nullable<long> a_idpcianacimiento
		{
			get
			{
				return this._a_idpcianacimiento;
			}
			set
			{
				if ((this._a_idpcianacimiento != value))
				{
					if (this._Provincia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ona_idpcianacimientoChanging(value);
					this.SendPropertyChanging();
					this._a_idpcianacimiento = value;
					this.SendPropertyChanged("a_idpcianacimiento");
					this.Ona_idpcianacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_idpaisnacimiento", DbType="BigInt")]
		public System.Nullable<long> a_idpaisnacimiento
		{
			get
			{
				return this._a_idpaisnacimiento;
			}
			set
			{
				if ((this._a_idpaisnacimiento != value))
				{
					if (this._Pais.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ona_idpaisnacimientoChanging(value);
					this.SendPropertyChanging();
					this._a_idpaisnacimiento = value;
					this.SendPropertyChanged("a_idpaisnacimiento");
					this.Ona_idpaisnacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_mail", DbType="NVarChar(50)")]
		public string a_mail
		{
			get
			{
				return this._a_mail;
			}
			set
			{
				if ((this._a_mail != value))
				{
					this.Ona_mailChanging(value);
					this.SendPropertyChanging();
					this._a_mail = value;
					this.SendPropertyChanged("a_mail");
					this.Ona_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_cuil", DbType="NChar(20)")]
		public string a_cuil
		{
			get
			{
				return this._a_cuil;
			}
			set
			{
				if ((this._a_cuil != value))
				{
					this.Ona_cuilChanging(value);
					this.SendPropertyChanging();
					this._a_cuil = value;
					this.SendPropertyChanged("a_cuil");
					this.Ona_cuilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_telefonofijo", DbType="NVarChar(50)")]
		public string a_telefonofijo
		{
			get
			{
				return this._a_telefonofijo;
			}
			set
			{
				if ((this._a_telefonofijo != value))
				{
					this.Ona_telefonofijoChanging(value);
					this.SendPropertyChanging();
					this._a_telefonofijo = value;
					this.SendPropertyChanged("a_telefonofijo");
					this.Ona_telefonofijoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_telefonocelular", DbType="NVarChar(50)")]
		public string a_telefonocelular
		{
			get
			{
				return this._a_telefonocelular;
			}
			set
			{
				if ((this._a_telefonocelular != value))
				{
					this.Ona_telefonocelularChanging(value);
					this.SendPropertyChanging();
					this._a_telefonocelular = value;
					this.SendPropertyChanged("a_telefonocelular");
					this.Ona_telefonocelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_contactoemergencia", DbType="NVarChar(MAX)")]
		public string a_contactoemergencia
		{
			get
			{
				return this._a_contactoemergencia;
			}
			set
			{
				if ((this._a_contactoemergencia != value))
				{
					this.Ona_contactoemergenciaChanging(value);
					this.SendPropertyChanging();
					this._a_contactoemergencia = value;
					this.SendPropertyChanged("a_contactoemergencia");
					this.Ona_contactoemergenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_direccionresidencia", DbType="NVarChar(MAX)")]
		public string a_direccionresidencia
		{
			get
			{
				return this._a_direccionresidencia;
			}
			set
			{
				if ((this._a_direccionresidencia != value))
				{
					this.Ona_direccionresidenciaChanging(value);
					this.SendPropertyChanging();
					this._a_direccionresidencia = value;
					this.SendPropertyChanged("a_direccionresidencia");
					this.Ona_direccionresidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_idciudadresidencia", DbType="BigInt")]
		public System.Nullable<long> a_idciudadresidencia
		{
			get
			{
				return this._a_idciudadresidencia;
			}
			set
			{
				if ((this._a_idciudadresidencia != value))
				{
					if (this._Ciudad1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ona_idciudadresidenciaChanging(value);
					this.SendPropertyChanging();
					this._a_idciudadresidencia = value;
					this.SendPropertyChanged("a_idciudadresidencia");
					this.Ona_idciudadresidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_pciaresidencia", DbType="BigInt")]
		public System.Nullable<long> a_pciaresidencia
		{
			get
			{
				return this._a_pciaresidencia;
			}
			set
			{
				if ((this._a_pciaresidencia != value))
				{
					if (this._Provincia1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ona_pciaresidenciaChanging(value);
					this.SendPropertyChanging();
					this._a_pciaresidencia = value;
					this.SendPropertyChanged("a_pciaresidencia");
					this.Ona_pciaresidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_paisresidencia", DbType="BigInt")]
		public System.Nullable<long> a_paisresidencia
		{
			get
			{
				return this._a_paisresidencia;
			}
			set
			{
				if ((this._a_paisresidencia != value))
				{
					if (this._Pais1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ona_paisresidenciaChanging(value);
					this.SendPropertyChanging();
					this._a_paisresidencia = value;
					this.SendPropertyChanged("a_paisresidencia");
					this.Ona_paisresidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_telefonofijoresidencia", DbType="NVarChar(50)")]
		public string a_telefonofijoresidencia
		{
			get
			{
				return this._a_telefonofijoresidencia;
			}
			set
			{
				if ((this._a_telefonofijoresidencia != value))
				{
					this.Ona_telefonofijoresidenciaChanging(value);
					this.SendPropertyChanging();
					this._a_telefonofijoresidencia = value;
					this.SendPropertyChanged("a_telefonofijoresidencia");
					this.Ona_telefonofijoresidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_telefonocelularresidencia", DbType="NVarChar(50)")]
		public string a_telefonocelularresidencia
		{
			get
			{
				return this._a_telefonocelularresidencia;
			}
			set
			{
				if ((this._a_telefonocelularresidencia != value))
				{
					this.Ona_telefonocelularresidenciaChanging(value);
					this.SendPropertyChanging();
					this._a_telefonocelularresidencia = value;
					this.SendPropertyChanged("a_telefonocelularresidencia");
					this.Ona_telefonocelularresidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_activo", DbType="Int")]
		public System.Nullable<int> a_activo
		{
			get
			{
				return this._a_activo;
			}
			set
			{
				if ((this._a_activo != value))
				{
					this.Ona_activoChanging(value);
					this.SendPropertyChanging();
					this._a_activo = value;
					this.SendPropertyChanged("a_activo");
					this.Ona_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_fechaaltasistema", DbType="DateTime")]
		public System.Nullable<System.DateTime> a_fechaaltasistema
		{
			get
			{
				return this._a_fechaaltasistema;
			}
			set
			{
				if ((this._a_fechaaltasistema != value))
				{
					this.Ona_fechaaltasistemaChanging(value);
					this.SendPropertyChanging();
					this._a_fechaaltasistema = value;
					this.SendPropertyChanged("a_fechaaltasistema");
					this.Ona_fechaaltasistemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_fechaultimaactualizacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> a_fechaultimaactualizacion
		{
			get
			{
				return this._a_fechaultimaactualizacion;
			}
			set
			{
				if ((this._a_fechaultimaactualizacion != value))
				{
					this.Ona_fechaultimaactualizacionChanging(value);
					this.SendPropertyChanging();
					this._a_fechaultimaactualizacion = value;
					this.SendPropertyChanged("a_fechaultimaactualizacion");
					this.Ona_fechaultimaactualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary a_foto
		{
			get
			{
				return this._a_foto;
			}
			set
			{
				if ((this._a_foto != value))
				{
					this.Ona_fotoChanging(value);
					this.SendPropertyChanging();
					this._a_foto = value;
					this.SendPropertyChanged("a_foto");
					this.Ona_fotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivelestudio", DbType="BigInt")]
		public System.Nullable<long> Nivelestudio
		{
			get
			{
				return this._Nivelestudio;
			}
			set
			{
				if ((this._Nivelestudio != value))
				{
					this.OnNivelestudioChanging(value);
					this.SendPropertyChanging();
					this._Nivelestudio = value;
					this.SendPropertyChanged("Nivelestudio");
					this.OnNivelestudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idtipousuario", DbType="BigInt")]
		public System.Nullable<long> Idtipousuario
		{
			get
			{
				return this._Idtipousuario;
			}
			set
			{
				if ((this._Idtipousuario != value))
				{
					if (this._TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdtipousuarioChanging(value);
					this.SendPropertyChanging();
					this._Idtipousuario = value;
					this.SendPropertyChanged("Idtipousuario");
					this.OnIdtipousuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_Idempresa", DbType="BigInt")]
		public System.Nullable<long> a_Idempresa
		{
			get
			{
				return this._a_Idempresa;
			}
			set
			{
				if ((this._a_Idempresa != value))
				{
					this.Ona_IdempresaChanging(value);
					this.SendPropertyChanging();
					this._a_Idempresa = value;
					this.SendPropertyChanged("a_Idempresa");
					this.Ona_IdempresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_idmodoingreso", DbType="BigInt")]
		public System.Nullable<long> a_idmodoingreso
		{
			get
			{
				return this._a_idmodoingreso;
			}
			set
			{
				if ((this._a_idmodoingreso != value))
				{
					this.Ona_idmodoingresoChanging(value);
					this.SendPropertyChanging();
					this._a_idmodoingreso = value;
					this.SendPropertyChanged("a_idmodoingreso");
					this.Ona_idmodoingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_idestadoalumno", DbType="BigInt")]
		public System.Nullable<long> a_idestadoalumno
		{
			get
			{
				return this._a_idestadoalumno;
			}
			set
			{
				if ((this._a_idestadoalumno != value))
				{
					this.Ona_idestadoalumnoChanging(value);
					this.SendPropertyChanging();
					this._a_idestadoalumno = value;
					this.SendPropertyChanged("a_idestadoalumno");
					this.Ona_idestadoalumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_Alumno", Storage="_Ciudad", ThisKey="a_id_ciudadnacimiento", OtherKey="id_ciudad", IsForeignKey=true)]
		public Ciudad Ciudad
		{
			get
			{
				return this._Ciudad.Entity;
			}
			set
			{
				Ciudad previousValue = this._Ciudad.Entity;
				if (((previousValue != value) 
							|| (this._Ciudad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciudad.Entity = null;
						previousValue.Alumno.Remove(this);
					}
					this._Ciudad.Entity = value;
					if ((value != null))
					{
						value.Alumno.Add(this);
						this._a_id_ciudadnacimiento = value.id_ciudad;
					}
					else
					{
						this._a_id_ciudadnacimiento = default(Nullable<long>);
					}
					this.SendPropertyChanged("Ciudad");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_Alumno1", Storage="_Ciudad1", ThisKey="a_idciudadresidencia", OtherKey="id_ciudad", IsForeignKey=true)]
		public Ciudad Ciudad1
		{
			get
			{
				return this._Ciudad1.Entity;
			}
			set
			{
				Ciudad previousValue = this._Ciudad1.Entity;
				if (((previousValue != value) 
							|| (this._Ciudad1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciudad1.Entity = null;
						previousValue.Alumno1.Remove(this);
					}
					this._Ciudad1.Entity = value;
					if ((value != null))
					{
						value.Alumno1.Add(this);
						this._a_idciudadresidencia = value.id_ciudad;
					}
					else
					{
						this._a_idciudadresidencia = default(Nullable<long>);
					}
					this.SendPropertyChanged("Ciudad1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pais_Alumno", Storage="_Pais", ThisKey="a_idpaisnacimiento", OtherKey="Id_pais", IsForeignKey=true)]
		public Pais Pais
		{
			get
			{
				return this._Pais.Entity;
			}
			set
			{
				Pais previousValue = this._Pais.Entity;
				if (((previousValue != value) 
							|| (this._Pais.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pais.Entity = null;
						previousValue.Alumno.Remove(this);
					}
					this._Pais.Entity = value;
					if ((value != null))
					{
						value.Alumno.Add(this);
						this._a_idpaisnacimiento = value.Id_pais;
					}
					else
					{
						this._a_idpaisnacimiento = default(Nullable<long>);
					}
					this.SendPropertyChanged("Pais");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pais_Alumno1", Storage="_Pais1", ThisKey="a_paisresidencia", OtherKey="Id_pais", IsForeignKey=true)]
		public Pais Pais1
		{
			get
			{
				return this._Pais1.Entity;
			}
			set
			{
				Pais previousValue = this._Pais1.Entity;
				if (((previousValue != value) 
							|| (this._Pais1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pais1.Entity = null;
						previousValue.Alumno1.Remove(this);
					}
					this._Pais1.Entity = value;
					if ((value != null))
					{
						value.Alumno1.Add(this);
						this._a_paisresidencia = value.Id_pais;
					}
					else
					{
						this._a_paisresidencia = default(Nullable<long>);
					}
					this.SendPropertyChanged("Pais1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Alumno", Storage="_Provincia", ThisKey="a_idpcianacimiento", OtherKey="id_provincia", IsForeignKey=true)]
		public Provincia Provincia
		{
			get
			{
				return this._Provincia.Entity;
			}
			set
			{
				Provincia previousValue = this._Provincia.Entity;
				if (((previousValue != value) 
							|| (this._Provincia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincia.Entity = null;
						previousValue.Alumno.Remove(this);
					}
					this._Provincia.Entity = value;
					if ((value != null))
					{
						value.Alumno.Add(this);
						this._a_idpcianacimiento = value.id_provincia;
					}
					else
					{
						this._a_idpcianacimiento = default(Nullable<long>);
					}
					this.SendPropertyChanged("Provincia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Alumno1", Storage="_Provincia1", ThisKey="a_pciaresidencia", OtherKey="id_provincia", IsForeignKey=true)]
		public Provincia Provincia1
		{
			get
			{
				return this._Provincia1.Entity;
			}
			set
			{
				Provincia previousValue = this._Provincia1.Entity;
				if (((previousValue != value) 
							|| (this._Provincia1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincia1.Entity = null;
						previousValue.Alumno1.Remove(this);
					}
					this._Provincia1.Entity = value;
					if ((value != null))
					{
						value.Alumno1.Add(this);
						this._a_pciaresidencia = value.id_provincia;
					}
					else
					{
						this._a_pciaresidencia = default(Nullable<long>);
					}
					this.SendPropertyChanged("Provincia1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Alumno", Storage="_TipoUsuario", ThisKey="Idtipousuario", OtherKey="Id_tipousuario", IsForeignKey=true)]
		public TipoUsuario TipoUsuario
		{
			get
			{
				return this._TipoUsuario.Entity;
			}
			set
			{
				TipoUsuario previousValue = this._TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoUsuario.Entity = null;
						previousValue.Alumno.Remove(this);
					}
					this._TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Alumno.Add(this);
						this._Idtipousuario = value.Id_tipousuario;
					}
					else
					{
						this._Idtipousuario = default(Nullable<long>);
					}
					this.SendPropertyChanged("TipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_usuario;
		
		private string _NombreUsuario;
		
		private string _Contraseña;
		
		private System.Nullable<long> _TipoUsuario;
		
		private System.Nullable<long> _Id_AlumnoPersonal;
		
		private System.Nullable<long> _IdRol;
		
		private System.Nullable<int> _Activo;
		
		private System.Nullable<long> _Nivel_Estudio;
		
		private System.Nullable<long> _Id_empresa;
		
		private string _Nombres;
		
		private string _Apellido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_usuarioChanging(long value);
    partial void OnId_usuarioChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnTipoUsuarioChanging(System.Nullable<long> value);
    partial void OnTipoUsuarioChanged();
    partial void OnId_AlumnoPersonalChanging(System.Nullable<long> value);
    partial void OnId_AlumnoPersonalChanged();
    partial void OnIdRolChanging(System.Nullable<long> value);
    partial void OnIdRolChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    partial void OnNivel_EstudioChanging(System.Nullable<long> value);
    partial void OnNivel_EstudioChanged();
    partial void OnId_empresaChanging(System.Nullable<long> value);
    partial void OnId_empresaChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_usuario", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id_usuario
		{
			get
			{
				return this._Id_usuario;
			}
			set
			{
				if ((this._Id_usuario != value))
				{
					this.OnId_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_usuario = value;
					this.SendPropertyChanged("Id_usuario");
					this.OnId_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(MAX)")]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NVarChar(70)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuario", DbType="BigInt")]
		public System.Nullable<long> TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this.OnTipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._TipoUsuario = value;
					this.SendPropertyChanged("TipoUsuario");
					this.OnTipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_AlumnoPersonal", DbType="BigInt")]
		public System.Nullable<long> Id_AlumnoPersonal
		{
			get
			{
				return this._Id_AlumnoPersonal;
			}
			set
			{
				if ((this._Id_AlumnoPersonal != value))
				{
					this.OnId_AlumnoPersonalChanging(value);
					this.SendPropertyChanging();
					this._Id_AlumnoPersonal = value;
					this.SendPropertyChanged("Id_AlumnoPersonal");
					this.OnId_AlumnoPersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="BigInt")]
		public System.Nullable<long> IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this.OnIdRolChanging(value);
					this.SendPropertyChanging();
					this._IdRol = value;
					this.SendPropertyChanged("IdRol");
					this.OnIdRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_Estudio", DbType="BigInt")]
		public System.Nullable<long> Nivel_Estudio
		{
			get
			{
				return this._Nivel_Estudio;
			}
			set
			{
				if ((this._Nivel_Estudio != value))
				{
					this.OnNivel_EstudioChanging(value);
					this.SendPropertyChanging();
					this._Nivel_Estudio = value;
					this.SendPropertyChanged("Nivel_Estudio");
					this.OnNivel_EstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_empresa", DbType="BigInt")]
		public System.Nullable<long> Id_empresa
		{
			get
			{
				return this._Id_empresa;
			}
			set
			{
				if ((this._Id_empresa != value))
				{
					this.OnId_empresaChanging(value);
					this.SendPropertyChanging();
					this._Id_empresa = value;
					this.SendPropertyChanged("Id_empresa");
					this.OnId_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="NVarChar(50)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ciudad")]
	public partial class Ciudad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_ciudad;
		
		private string _Nombre;
		
		private System.Nullable<int> _Activo;
		
		private System.Nullable<long> _Id_empresa;
		
		private EntitySet<Alumno> _Alumno;
		
		private EntitySet<Alumno> _Alumno1;
		
		private EntitySet<PersonalDocenteNoDocente> _PersonalDocenteNoDocente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ciudadChanging(long value);
    partial void Onid_ciudadChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    partial void OnId_empresaChanging(System.Nullable<long> value);
    partial void OnId_empresaChanged();
    #endregion
		
		public Ciudad()
		{
			this._Alumno = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno), new Action<Alumno>(this.detach_Alumno));
			this._Alumno1 = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno1), new Action<Alumno>(this.detach_Alumno1));
			this._PersonalDocenteNoDocente = new EntitySet<PersonalDocenteNoDocente>(new Action<PersonalDocenteNoDocente>(this.attach_PersonalDocenteNoDocente), new Action<PersonalDocenteNoDocente>(this.detach_PersonalDocenteNoDocente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ciudad", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id_ciudad
		{
			get
			{
				return this._id_ciudad;
			}
			set
			{
				if ((this._id_ciudad != value))
				{
					this.Onid_ciudadChanging(value);
					this.SendPropertyChanging();
					this._id_ciudad = value;
					this.SendPropertyChanged("id_ciudad");
					this.Onid_ciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(150)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_empresa", DbType="BigInt")]
		public System.Nullable<long> Id_empresa
		{
			get
			{
				return this._Id_empresa;
			}
			set
			{
				if ((this._Id_empresa != value))
				{
					this.OnId_empresaChanging(value);
					this.SendPropertyChanging();
					this._Id_empresa = value;
					this.SendPropertyChanged("Id_empresa");
					this.OnId_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_Alumno", Storage="_Alumno", ThisKey="id_ciudad", OtherKey="a_id_ciudadnacimiento")]
		public EntitySet<Alumno> Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				this._Alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_Alumno1", Storage="_Alumno1", ThisKey="id_ciudad", OtherKey="a_idciudadresidencia")]
		public EntitySet<Alumno> Alumno1
		{
			get
			{
				return this._Alumno1;
			}
			set
			{
				this._Alumno1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_PersonalDocenteNoDocente", Storage="_PersonalDocenteNoDocente", ThisKey="id_ciudad", OtherKey="Idciudad")]
		public EntitySet<PersonalDocenteNoDocente> PersonalDocenteNoDocente
		{
			get
			{
				return this._PersonalDocenteNoDocente;
			}
			set
			{
				this._PersonalDocenteNoDocente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Ciudad = this;
		}
		
		private void detach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Ciudad = null;
		}
		
		private void attach_Alumno1(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Ciudad1 = this;
		}
		
		private void detach_Alumno1(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Ciudad1 = null;
		}
		
		private void attach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.Ciudad = this;
		}
		
		private void detach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.Ciudad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pais")]
	public partial class Pais : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_pais;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Activo;
		
		private EntitySet<Alumno> _Alumno;
		
		private EntitySet<Alumno> _Alumno1;
		
		private EntitySet<PersonalDocenteNoDocente> _PersonalDocenteNoDocente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_paisChanging(long value);
    partial void OnId_paisChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    #endregion
		
		public Pais()
		{
			this._Alumno = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno), new Action<Alumno>(this.detach_Alumno));
			this._Alumno1 = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno1), new Action<Alumno>(this.detach_Alumno1));
			this._PersonalDocenteNoDocente = new EntitySet<PersonalDocenteNoDocente>(new Action<PersonalDocenteNoDocente>(this.attach_PersonalDocenteNoDocente), new Action<PersonalDocenteNoDocente>(this.detach_PersonalDocenteNoDocente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pais", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_pais
		{
			get
			{
				return this._Id_pais;
			}
			set
			{
				if ((this._Id_pais != value))
				{
					this.OnId_paisChanging(value);
					this.SendPropertyChanging();
					this._Id_pais = value;
					this.SendPropertyChanged("Id_pais");
					this.OnId_paisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pais_Alumno", Storage="_Alumno", ThisKey="Id_pais", OtherKey="a_idpaisnacimiento")]
		public EntitySet<Alumno> Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				this._Alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pais_Alumno1", Storage="_Alumno1", ThisKey="Id_pais", OtherKey="a_paisresidencia")]
		public EntitySet<Alumno> Alumno1
		{
			get
			{
				return this._Alumno1;
			}
			set
			{
				this._Alumno1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pais_PersonalDocenteNoDocente", Storage="_PersonalDocenteNoDocente", ThisKey="Id_pais", OtherKey="Idpais")]
		public EntitySet<PersonalDocenteNoDocente> PersonalDocenteNoDocente
		{
			get
			{
				return this._PersonalDocenteNoDocente;
			}
			set
			{
				this._PersonalDocenteNoDocente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Pais = this;
		}
		
		private void detach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Pais = null;
		}
		
		private void attach_Alumno1(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Pais1 = this;
		}
		
		private void detach_Alumno1(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Pais1 = null;
		}
		
		private void attach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.Pais = this;
		}
		
		private void detach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.Pais = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonalDocenteNoDocente")]
	public partial class PersonalDocenteNoDocente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_personal;
		
		private System.Nullable<long> _Idtipopersonal;
		
		private string _Nrodocumento;
		
		private System.Nullable<long> _Tipodocumento;
		
		private string _Cuil;
		
		private string _Apellido;
		
		private string _Nombre;
		
		private System.Nullable<long> _Sexo;
		
		private System.DateTime _Fechanacimiento;
		
		private string _Telefonocelular;
		
		private string _Telefonofijo;
		
		private string _Email;
		
		private string _Direccion;
		
		private string _Barrio;
		
		private System.Nullable<long> _Idciudad;
		
		private System.Nullable<long> _Idprovincia;
		
		private System.Nullable<long> _Idpais;
		
		private string _Observaciones;
		
		private System.Nullable<int> _Activo;
		
		private System.Nullable<System.DateTime> _Fechaalta;
		
		private System.Nullable<System.DateTime> _Fechaactualizacion;
		
		private System.Data.Linq.Binary _Foto;
		
		private System.Nullable<long> _Ciudadnacimiento;
		
		private System.Nullable<long> _Provincianacimiento;
		
		private System.Nullable<long> _Paisnacimiento;
		
		private System.Nullable<long> _Nivelestudio;
		
		private System.Nullable<long> _Idtipousuario;
		
		private System.Nullable<long> _Id_empresa;
		
		private EntityRef<Ciudad> _Ciudad;
		
		private EntityRef<Pais> _Pais;
		
		private EntityRef<Provincia> _Provincia;
		
		private EntityRef<Sexo> _Sexo1;
		
		private EntityRef<TipoDocumento> _TipoDocumento1;
		
		private EntityRef<TipoUsuario> _TipoUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_personalChanging(long value);
    partial void OnId_personalChanged();
    partial void OnIdtipopersonalChanging(System.Nullable<long> value);
    partial void OnIdtipopersonalChanged();
    partial void OnNrodocumentoChanging(string value);
    partial void OnNrodocumentoChanged();
    partial void OnTipodocumentoChanging(System.Nullable<long> value);
    partial void OnTipodocumentoChanged();
    partial void OnCuilChanging(string value);
    partial void OnCuilChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnSexoChanging(System.Nullable<long> value);
    partial void OnSexoChanged();
    partial void OnFechanacimientoChanging(System.DateTime value);
    partial void OnFechanacimientoChanged();
    partial void OnTelefonocelularChanging(string value);
    partial void OnTelefonocelularChanged();
    partial void OnTelefonofijoChanging(string value);
    partial void OnTelefonofijoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnBarrioChanging(string value);
    partial void OnBarrioChanged();
    partial void OnIdciudadChanging(System.Nullable<long> value);
    partial void OnIdciudadChanged();
    partial void OnIdprovinciaChanging(System.Nullable<long> value);
    partial void OnIdprovinciaChanged();
    partial void OnIdpaisChanging(System.Nullable<long> value);
    partial void OnIdpaisChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    partial void OnFechaaltaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaaltaChanged();
    partial void OnFechaactualizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaactualizacionChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnCiudadnacimientoChanging(System.Nullable<long> value);
    partial void OnCiudadnacimientoChanged();
    partial void OnProvincianacimientoChanging(System.Nullable<long> value);
    partial void OnProvincianacimientoChanged();
    partial void OnPaisnacimientoChanging(System.Nullable<long> value);
    partial void OnPaisnacimientoChanged();
    partial void OnNivelestudioChanging(System.Nullable<long> value);
    partial void OnNivelestudioChanged();
    partial void OnIdtipousuarioChanging(System.Nullable<long> value);
    partial void OnIdtipousuarioChanged();
    partial void OnId_empresaChanging(System.Nullable<long> value);
    partial void OnId_empresaChanged();
    #endregion
		
		public PersonalDocenteNoDocente()
		{
			this._Ciudad = default(EntityRef<Ciudad>);
			this._Pais = default(EntityRef<Pais>);
			this._Provincia = default(EntityRef<Provincia>);
			this._Sexo1 = default(EntityRef<Sexo>);
			this._TipoDocumento1 = default(EntityRef<TipoDocumento>);
			this._TipoUsuario = default(EntityRef<TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_personal", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id_personal
		{
			get
			{
				return this._Id_personal;
			}
			set
			{
				if ((this._Id_personal != value))
				{
					this.OnId_personalChanging(value);
					this.SendPropertyChanging();
					this._Id_personal = value;
					this.SendPropertyChanged("Id_personal");
					this.OnId_personalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idtipopersonal", DbType="BigInt")]
		public System.Nullable<long> Idtipopersonal
		{
			get
			{
				return this._Idtipopersonal;
			}
			set
			{
				if ((this._Idtipopersonal != value))
				{
					this.OnIdtipopersonalChanging(value);
					this.SendPropertyChanging();
					this._Idtipopersonal = value;
					this.SendPropertyChanged("Idtipopersonal");
					this.OnIdtipopersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nrodocumento", DbType="NVarChar(20)")]
		public string Nrodocumento
		{
			get
			{
				return this._Nrodocumento;
			}
			set
			{
				if ((this._Nrodocumento != value))
				{
					this.OnNrodocumentoChanging(value);
					this.SendPropertyChanging();
					this._Nrodocumento = value;
					this.SendPropertyChanged("Nrodocumento");
					this.OnNrodocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipodocumento", DbType="BigInt")]
		public System.Nullable<long> Tipodocumento
		{
			get
			{
				return this._Tipodocumento;
			}
			set
			{
				if ((this._Tipodocumento != value))
				{
					if (this._TipoDocumento1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipodocumentoChanging(value);
					this.SendPropertyChanging();
					this._Tipodocumento = value;
					this.SendPropertyChanged("Tipodocumento");
					this.OnTipodocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuil", DbType="NVarChar(50)")]
		public string Cuil
		{
			get
			{
				return this._Cuil;
			}
			set
			{
				if ((this._Cuil != value))
				{
					this.OnCuilChanging(value);
					this.SendPropertyChanging();
					this._Cuil = value;
					this.SendPropertyChanged("Cuil");
					this.OnCuilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(MAX)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(MAX)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="BigInt")]
		public System.Nullable<long> Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					if (this._Sexo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fechanacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime Fechanacimiento
		{
			get
			{
				return this._Fechanacimiento;
			}
			set
			{
				if ((this._Fechanacimiento != value))
				{
					this.OnFechanacimientoChanging(value);
					this.SendPropertyChanging();
					this._Fechanacimiento = value;
					this.SendPropertyChanged("Fechanacimiento");
					this.OnFechanacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonocelular", DbType="NVarChar(50)")]
		public string Telefonocelular
		{
			get
			{
				return this._Telefonocelular;
			}
			set
			{
				if ((this._Telefonocelular != value))
				{
					this.OnTelefonocelularChanging(value);
					this.SendPropertyChanging();
					this._Telefonocelular = value;
					this.SendPropertyChanged("Telefonocelular");
					this.OnTelefonocelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonofijo", DbType="NVarChar(50)")]
		public string Telefonofijo
		{
			get
			{
				return this._Telefonofijo;
			}
			set
			{
				if ((this._Telefonofijo != value))
				{
					this.OnTelefonofijoChanging(value);
					this.SendPropertyChanging();
					this._Telefonofijo = value;
					this.SendPropertyChanged("Telefonofijo");
					this.OnTelefonofijoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(MAX)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barrio", DbType="NVarChar(50)")]
		public string Barrio
		{
			get
			{
				return this._Barrio;
			}
			set
			{
				if ((this._Barrio != value))
				{
					this.OnBarrioChanging(value);
					this.SendPropertyChanging();
					this._Barrio = value;
					this.SendPropertyChanged("Barrio");
					this.OnBarrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idciudad", DbType="BigInt")]
		public System.Nullable<long> Idciudad
		{
			get
			{
				return this._Idciudad;
			}
			set
			{
				if ((this._Idciudad != value))
				{
					if (this._Ciudad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdciudadChanging(value);
					this.SendPropertyChanging();
					this._Idciudad = value;
					this.SendPropertyChanged("Idciudad");
					this.OnIdciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idprovincia", DbType="BigInt")]
		public System.Nullable<long> Idprovincia
		{
			get
			{
				return this._Idprovincia;
			}
			set
			{
				if ((this._Idprovincia != value))
				{
					if (this._Provincia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdprovinciaChanging(value);
					this.SendPropertyChanging();
					this._Idprovincia = value;
					this.SendPropertyChanged("Idprovincia");
					this.OnIdprovinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpais", DbType="BigInt")]
		public System.Nullable<long> Idpais
		{
			get
			{
				return this._Idpais;
			}
			set
			{
				if ((this._Idpais != value))
				{
					if (this._Pais.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdpaisChanging(value);
					this.SendPropertyChanging();
					this._Idpais = value;
					this.SendPropertyChanged("Idpais");
					this.OnIdpaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="NVarChar(MAX)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fechaalta", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fechaalta
		{
			get
			{
				return this._Fechaalta;
			}
			set
			{
				if ((this._Fechaalta != value))
				{
					this.OnFechaaltaChanging(value);
					this.SendPropertyChanging();
					this._Fechaalta = value;
					this.SendPropertyChanged("Fechaalta");
					this.OnFechaaltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fechaactualizacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fechaactualizacion
		{
			get
			{
				return this._Fechaactualizacion;
			}
			set
			{
				if ((this._Fechaactualizacion != value))
				{
					this.OnFechaactualizacionChanging(value);
					this.SendPropertyChanging();
					this._Fechaactualizacion = value;
					this.SendPropertyChanged("Fechaactualizacion");
					this.OnFechaactualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudadnacimiento", DbType="BigInt")]
		public System.Nullable<long> Ciudadnacimiento
		{
			get
			{
				return this._Ciudadnacimiento;
			}
			set
			{
				if ((this._Ciudadnacimiento != value))
				{
					this.OnCiudadnacimientoChanging(value);
					this.SendPropertyChanging();
					this._Ciudadnacimiento = value;
					this.SendPropertyChanged("Ciudadnacimiento");
					this.OnCiudadnacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincianacimiento", DbType="BigInt")]
		public System.Nullable<long> Provincianacimiento
		{
			get
			{
				return this._Provincianacimiento;
			}
			set
			{
				if ((this._Provincianacimiento != value))
				{
					this.OnProvincianacimientoChanging(value);
					this.SendPropertyChanging();
					this._Provincianacimiento = value;
					this.SendPropertyChanged("Provincianacimiento");
					this.OnProvincianacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paisnacimiento", DbType="BigInt")]
		public System.Nullable<long> Paisnacimiento
		{
			get
			{
				return this._Paisnacimiento;
			}
			set
			{
				if ((this._Paisnacimiento != value))
				{
					this.OnPaisnacimientoChanging(value);
					this.SendPropertyChanging();
					this._Paisnacimiento = value;
					this.SendPropertyChanged("Paisnacimiento");
					this.OnPaisnacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivelestudio", DbType="BigInt")]
		public System.Nullable<long> Nivelestudio
		{
			get
			{
				return this._Nivelestudio;
			}
			set
			{
				if ((this._Nivelestudio != value))
				{
					this.OnNivelestudioChanging(value);
					this.SendPropertyChanging();
					this._Nivelestudio = value;
					this.SendPropertyChanged("Nivelestudio");
					this.OnNivelestudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idtipousuario", DbType="BigInt")]
		public System.Nullable<long> Idtipousuario
		{
			get
			{
				return this._Idtipousuario;
			}
			set
			{
				if ((this._Idtipousuario != value))
				{
					if (this._TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdtipousuarioChanging(value);
					this.SendPropertyChanging();
					this._Idtipousuario = value;
					this.SendPropertyChanged("Idtipousuario");
					this.OnIdtipousuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_empresa", DbType="BigInt")]
		public System.Nullable<long> Id_empresa
		{
			get
			{
				return this._Id_empresa;
			}
			set
			{
				if ((this._Id_empresa != value))
				{
					this.OnId_empresaChanging(value);
					this.SendPropertyChanging();
					this._Id_empresa = value;
					this.SendPropertyChanged("Id_empresa");
					this.OnId_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_PersonalDocenteNoDocente", Storage="_Ciudad", ThisKey="Idciudad", OtherKey="id_ciudad", IsForeignKey=true)]
		public Ciudad Ciudad
		{
			get
			{
				return this._Ciudad.Entity;
			}
			set
			{
				Ciudad previousValue = this._Ciudad.Entity;
				if (((previousValue != value) 
							|| (this._Ciudad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciudad.Entity = null;
						previousValue.PersonalDocenteNoDocente.Remove(this);
					}
					this._Ciudad.Entity = value;
					if ((value != null))
					{
						value.PersonalDocenteNoDocente.Add(this);
						this._Idciudad = value.id_ciudad;
					}
					else
					{
						this._Idciudad = default(Nullable<long>);
					}
					this.SendPropertyChanged("Ciudad");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pais_PersonalDocenteNoDocente", Storage="_Pais", ThisKey="Idpais", OtherKey="Id_pais", IsForeignKey=true)]
		public Pais Pais
		{
			get
			{
				return this._Pais.Entity;
			}
			set
			{
				Pais previousValue = this._Pais.Entity;
				if (((previousValue != value) 
							|| (this._Pais.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pais.Entity = null;
						previousValue.PersonalDocenteNoDocente.Remove(this);
					}
					this._Pais.Entity = value;
					if ((value != null))
					{
						value.PersonalDocenteNoDocente.Add(this);
						this._Idpais = value.Id_pais;
					}
					else
					{
						this._Idpais = default(Nullable<long>);
					}
					this.SendPropertyChanged("Pais");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_PersonalDocenteNoDocente", Storage="_Provincia", ThisKey="Idprovincia", OtherKey="id_provincia", IsForeignKey=true)]
		public Provincia Provincia
		{
			get
			{
				return this._Provincia.Entity;
			}
			set
			{
				Provincia previousValue = this._Provincia.Entity;
				if (((previousValue != value) 
							|| (this._Provincia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincia.Entity = null;
						previousValue.PersonalDocenteNoDocente.Remove(this);
					}
					this._Provincia.Entity = value;
					if ((value != null))
					{
						value.PersonalDocenteNoDocente.Add(this);
						this._Idprovincia = value.id_provincia;
					}
					else
					{
						this._Idprovincia = default(Nullable<long>);
					}
					this.SendPropertyChanged("Provincia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sexo_PersonalDocenteNoDocente", Storage="_Sexo1", ThisKey="Sexo", OtherKey="Id_sexo", IsForeignKey=true)]
		public Sexo Sexo1
		{
			get
			{
				return this._Sexo1.Entity;
			}
			set
			{
				Sexo previousValue = this._Sexo1.Entity;
				if (((previousValue != value) 
							|| (this._Sexo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sexo1.Entity = null;
						previousValue.PersonalDocenteNoDocente.Remove(this);
					}
					this._Sexo1.Entity = value;
					if ((value != null))
					{
						value.PersonalDocenteNoDocente.Add(this);
						this._Sexo = value.Id_sexo;
					}
					else
					{
						this._Sexo = default(Nullable<long>);
					}
					this.SendPropertyChanged("Sexo1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoDocumento_PersonalDocenteNoDocente", Storage="_TipoDocumento1", ThisKey="Tipodocumento", OtherKey="Id_tipodocumento", IsForeignKey=true)]
		public TipoDocumento TipoDocumento1
		{
			get
			{
				return this._TipoDocumento1.Entity;
			}
			set
			{
				TipoDocumento previousValue = this._TipoDocumento1.Entity;
				if (((previousValue != value) 
							|| (this._TipoDocumento1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoDocumento1.Entity = null;
						previousValue.PersonalDocenteNoDocente.Remove(this);
					}
					this._TipoDocumento1.Entity = value;
					if ((value != null))
					{
						value.PersonalDocenteNoDocente.Add(this);
						this._Tipodocumento = value.Id_tipodocumento;
					}
					else
					{
						this._Tipodocumento = default(Nullable<long>);
					}
					this.SendPropertyChanged("TipoDocumento1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_PersonalDocenteNoDocente", Storage="_TipoUsuario", ThisKey="Idtipousuario", OtherKey="Id_tipousuario", IsForeignKey=true)]
		public TipoUsuario TipoUsuario
		{
			get
			{
				return this._TipoUsuario.Entity;
			}
			set
			{
				TipoUsuario previousValue = this._TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoUsuario.Entity = null;
						previousValue.PersonalDocenteNoDocente.Remove(this);
					}
					this._TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.PersonalDocenteNoDocente.Add(this);
						this._Idtipousuario = value.Id_tipousuario;
					}
					else
					{
						this._Idtipousuario = default(Nullable<long>);
					}
					this.SendPropertyChanged("TipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Provincia")]
	public partial class Provincia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id_provincia;
		
		private string _Descripcion;
		
		private string _Activo;
		
		private EntitySet<Alumno> _Alumno;
		
		private EntitySet<Alumno> _Alumno1;
		
		private EntitySet<PersonalDocenteNoDocente> _PersonalDocenteNoDocente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_provinciaChanging(long value);
    partial void Onid_provinciaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnActivoChanging(string value);
    partial void OnActivoChanged();
    #endregion
		
		public Provincia()
		{
			this._Alumno = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno), new Action<Alumno>(this.detach_Alumno));
			this._Alumno1 = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno1), new Action<Alumno>(this.detach_Alumno1));
			this._PersonalDocenteNoDocente = new EntitySet<PersonalDocenteNoDocente>(new Action<PersonalDocenteNoDocente>(this.attach_PersonalDocenteNoDocente), new Action<PersonalDocenteNoDocente>(this.detach_PersonalDocenteNoDocente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_provincia", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id_provincia
		{
			get
			{
				return this._id_provincia;
			}
			set
			{
				if ((this._id_provincia != value))
				{
					this.Onid_provinciaChanging(value);
					this.SendPropertyChanging();
					this._id_provincia = value;
					this.SendPropertyChanged("id_provincia");
					this.Onid_provinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="NChar(10)")]
		public string Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Alumno", Storage="_Alumno", ThisKey="id_provincia", OtherKey="a_idpcianacimiento")]
		public EntitySet<Alumno> Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				this._Alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Alumno1", Storage="_Alumno1", ThisKey="id_provincia", OtherKey="a_pciaresidencia")]
		public EntitySet<Alumno> Alumno1
		{
			get
			{
				return this._Alumno1;
			}
			set
			{
				this._Alumno1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_PersonalDocenteNoDocente", Storage="_PersonalDocenteNoDocente", ThisKey="id_provincia", OtherKey="Idprovincia")]
		public EntitySet<PersonalDocenteNoDocente> PersonalDocenteNoDocente
		{
			get
			{
				return this._PersonalDocenteNoDocente;
			}
			set
			{
				this._PersonalDocenteNoDocente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = this;
		}
		
		private void detach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = null;
		}
		
		private void attach_Alumno1(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Provincia1 = this;
		}
		
		private void detach_Alumno1(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Provincia1 = null;
		}
		
		private void attach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = this;
		}
		
		private void detach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sexo")]
	public partial class Sexo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_sexo;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Activo;
		
		private EntitySet<PersonalDocenteNoDocente> _PersonalDocenteNoDocente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_sexoChanging(long value);
    partial void OnId_sexoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    #endregion
		
		public Sexo()
		{
			this._PersonalDocenteNoDocente = new EntitySet<PersonalDocenteNoDocente>(new Action<PersonalDocenteNoDocente>(this.attach_PersonalDocenteNoDocente), new Action<PersonalDocenteNoDocente>(this.detach_PersonalDocenteNoDocente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_sexo", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_sexo
		{
			get
			{
				return this._Id_sexo;
			}
			set
			{
				if ((this._Id_sexo != value))
				{
					this.OnId_sexoChanging(value);
					this.SendPropertyChanging();
					this._Id_sexo = value;
					this.SendPropertyChanged("Id_sexo");
					this.OnId_sexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sexo_PersonalDocenteNoDocente", Storage="_PersonalDocenteNoDocente", ThisKey="Id_sexo", OtherKey="Sexo")]
		public EntitySet<PersonalDocenteNoDocente> PersonalDocenteNoDocente
		{
			get
			{
				return this._PersonalDocenteNoDocente;
			}
			set
			{
				this._PersonalDocenteNoDocente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.Sexo1 = this;
		}
		
		private void detach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.Sexo1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoDocumento")]
	public partial class TipoDocumento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_tipodocumento;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Activo;
		
		private EntitySet<PersonalDocenteNoDocente> _PersonalDocenteNoDocente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_tipodocumentoChanging(long value);
    partial void OnId_tipodocumentoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    #endregion
		
		public TipoDocumento()
		{
			this._PersonalDocenteNoDocente = new EntitySet<PersonalDocenteNoDocente>(new Action<PersonalDocenteNoDocente>(this.attach_PersonalDocenteNoDocente), new Action<PersonalDocenteNoDocente>(this.detach_PersonalDocenteNoDocente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tipodocumento", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_tipodocumento
		{
			get
			{
				return this._Id_tipodocumento;
			}
			set
			{
				if ((this._Id_tipodocumento != value))
				{
					this.OnId_tipodocumentoChanging(value);
					this.SendPropertyChanging();
					this._Id_tipodocumento = value;
					this.SendPropertyChanged("Id_tipodocumento");
					this.OnId_tipodocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoDocumento_PersonalDocenteNoDocente", Storage="_PersonalDocenteNoDocente", ThisKey="Id_tipodocumento", OtherKey="Tipodocumento")]
		public EntitySet<PersonalDocenteNoDocente> PersonalDocenteNoDocente
		{
			get
			{
				return this._PersonalDocenteNoDocente;
			}
			set
			{
				this._PersonalDocenteNoDocente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.TipoDocumento1 = this;
		}
		
		private void detach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.TipoDocumento1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoPersonal")]
	public partial class TipoPersonal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_tipopersonal;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Activo;
		
		private System.Nullable<long> _Nivelestudio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_tipopersonalChanging(long value);
    partial void OnId_tipopersonalChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    partial void OnNivelestudioChanging(System.Nullable<long> value);
    partial void OnNivelestudioChanged();
    #endregion
		
		public TipoPersonal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tipopersonal", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_tipopersonal
		{
			get
			{
				return this._Id_tipopersonal;
			}
			set
			{
				if ((this._Id_tipopersonal != value))
				{
					this.OnId_tipopersonalChanging(value);
					this.SendPropertyChanging();
					this._Id_tipopersonal = value;
					this.SendPropertyChanged("Id_tipopersonal");
					this.OnId_tipopersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivelestudio", DbType="BigInt")]
		public System.Nullable<long> Nivelestudio
		{
			get
			{
				return this._Nivelestudio;
			}
			set
			{
				if ((this._Nivelestudio != value))
				{
					this.OnNivelestudioChanging(value);
					this.SendPropertyChanging();
					this._Nivelestudio = value;
					this.SendPropertyChanged("Nivelestudio");
					this.OnNivelestudioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoUsuario")]
	public partial class TipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_tipousuario;
		
		private string _Nombre;
		
		private System.Nullable<int> _Activo;
		
		private System.Nullable<char> _Identificador;
		
		private EntitySet<Alumno> _Alumno;
		
		private EntitySet<PersonalDocenteNoDocente> _PersonalDocenteNoDocente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_tipousuarioChanging(long value);
    partial void OnId_tipousuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    partial void OnIdentificadorChanging(System.Nullable<char> value);
    partial void OnIdentificadorChanged();
    #endregion
		
		public TipoUsuario()
		{
			this._Alumno = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno), new Action<Alumno>(this.detach_Alumno));
			this._PersonalDocenteNoDocente = new EntitySet<PersonalDocenteNoDocente>(new Action<PersonalDocenteNoDocente>(this.attach_PersonalDocenteNoDocente), new Action<PersonalDocenteNoDocente>(this.detach_PersonalDocenteNoDocente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tipousuario", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_tipousuario
		{
			get
			{
				return this._Id_tipousuario;
			}
			set
			{
				if ((this._Id_tipousuario != value))
				{
					this.OnId_tipousuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_tipousuario = value;
					this.SendPropertyChanged("Id_tipousuario");
					this.OnId_tipousuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(MAX)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificador", DbType="NChar(1)")]
		public System.Nullable<char> Identificador
		{
			get
			{
				return this._Identificador;
			}
			set
			{
				if ((this._Identificador != value))
				{
					this.OnIdentificadorChanging(value);
					this.SendPropertyChanging();
					this._Identificador = value;
					this.SendPropertyChanged("Identificador");
					this.OnIdentificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Alumno", Storage="_Alumno", ThisKey="Id_tipousuario", OtherKey="Idtipousuario")]
		public EntitySet<Alumno> Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				this._Alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_PersonalDocenteNoDocente", Storage="_PersonalDocenteNoDocente", ThisKey="Id_tipousuario", OtherKey="Idtipousuario")]
		public EntitySet<PersonalDocenteNoDocente> PersonalDocenteNoDocente
		{
			get
			{
				return this._PersonalDocenteNoDocente;
			}
			set
			{
				this._PersonalDocenteNoDocente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = this;
		}
		
		private void detach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = null;
		}
		
		private void attach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = this;
		}
		
		private void detach_PersonalDocenteNoDocente(PersonalDocenteNoDocente entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = null;
		}
	}
}
#pragma warning restore 1591
